name: civexam_pro
description: CivExam ENA - Flutter app with white splash, square logo, and full questions folder
publish_to: "none"
version: 1.3.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8        # <-- AJOUTÉ
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0
  wakelock_plus: ^1.3.2
  flutter_windowmanager:
    path: third_party/flutter_windowmanager
  device_info_plus: ^10.0.0
  confetti: ^0.7.0
  image_picker: ^1.0.5
  diacritic: ^0.1.3
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  js: 0.6.7

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
    - assets/questions/ena_sample.json
    - assets/images/logo_splash.png
    - assets/images/background_playscreen.png
    - assets/icons/
    - assets/icons/mono/
    - assets/icons/sets/amber/
    - assets/icons/sets/grape/
    - assets/icons/sets/lime/
    - assets/icons/sets/teal/
    - assets/icons/sets/white/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/logo_splash.png
  fullscreen: true
  android: false
  ios: false
  web: false

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo_splash.png"
  adaptive_icon_background: "#37478F"
  adaptive_icon_foreground: "assets/images/logo_splash.png"
  min_sdk_android: 23
