name: civexam_pro
description: CivExam ENA - Flutter app with white splash, square logo, and full questions folder
publish_to: "none"
version: 1.3.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  firebase_core: 2.15.1
  firebase_core_web: 2.8.0
  firebase_auth: 4.15.3
  firebase_auth_web: 5.7.3
  cloud_firestore: 4.8.5
  cloud_firestore_web: 3.7.0
  firebase_storage: 11.2.4
  firebase_storage_web: 3.6.16
  wakelock_plus: ^1.3.2
  flutter_windowmanager:
    path: third_party/flutter_windowmanager
  device_info_plus: ^10.0.0
  confetti: ^0.7.0
  image_picker: ^1.0.5
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  js: 0.6.7

flutter:
  uses-material-design: true
  assets:
    - assets/questions/           # <-- inclut tout le dossier questions
    - assets/questions/ena_sample.json
    - assets/images/logo_splash_square.png
    - assets/images/logo_splash.png
    - assets/images/logo_icon_square.png
    - assets/icons/

    - assets/icons/mono/
    - assets/icons/sets/amber/
    - assets/icons/sets/grape/
    - assets/icons/sets/lime/
    - assets/icons/sets/teal/
    - assets/icons/sets/white/
# Splash (fond blanc + logo carré non rogné)
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/logo_splash_square.png
  fullscreen: true
  android: true
  ios: false
  web: false

# Icône Android (carrée paddée, compatible adaptive icons)
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo_icon_square.png"
  adaptive_icon_background: "#37478F"
  adaptive_icon_foreground: "assets/images/logo_icon_square.png"
  min_sdk_android: 21
